--CREATE VIEW view_adi
--AS
--SELECT sütun_adları
--FROM base _tablo_adı

CREATE VIEW KADINLAR
AS
SELECT * 
FROM CUSTOMERS
WHERE GENDER LIKE 'K%'

--SELECT * FROM KADINLAR
--DROP VIEW KADINLAR VIEW SILME