
DECLARE @EN_YASLI INT
SELECT @EN_YASLI=MAX(AGE) FROM CUSTOMERS

IF(@EN_YASLI>50)
BEGIN
	PRINT 'OLDUKCA YASLI MUSTERIMIZ'
END

ELSE IF(@EN_YASLI>40)
BEGIN
	PRINT 'OLDUKCA YASLI MUSTERIMIZ BI ALTI'
END
ELSE
BEGIN
	PRINT 'GENC MUSTERIMIZ'
END
GO
-- ----------------------------------------------------------------------------------------------------
--YAZACAGIMIZ IFADE TEK SATIRSA BEGIN END IFADESINI KULLANMAMIZA GEREK YOKTUR
--C++ DAKI FOR GIBI ASAGIDAKI IFADEDE CALISICAKTIR
--Kod bloğu tek satırdan oluşuyor ise BEGIN-END yazmaya gerek yoktur

DECLARE @EN_YASLI INT
SELECT @EN_YASLI=MAX(AGE) FROM CUSTOMERS

IF(@EN_YASLI>50)
	PRINT 'OLDUKCA YASLI MUSTERIMIZ'
ELSE IF(@EN_YASLI>40)
PRINT 'OLDUKCA YASLI MUSTERIMIZ BI ALTI'

ELSE
PRINT 'GENC MUSTERIMIZ'

GO




--tblUrun tablosunda hiç kayıt yok ise «Hiç kayıt yok» yazacak TSQL kodunu yazalım.

CREATE TABLE tblUrun
(
	ID INT  PRIMARY KEY IDENTITY(1,1) NOT NULL,
	ADI VARCHAR NOT NULL
)

IF NOT EXISTS(SELECT * FROM tblUrun)
PRINT 'HIC KAYT GIRILMEMIS(NULL)'
------------------------------------------
if NOT EXISTS(SELECT * FROM tblUrun)
PRINT 'Hiç ürün kaydı yok.'



