--use  Cqrs
-- sp_updatestats -- Update Statistic


--Cursor bir tablodan donen degerlerin içersinde donguyle donup bir takým iþleri sýralý bir þekilde yapmamýz demektir. => for gibi
DECLARE @NAMESURNAME AS VARCHAR(50) = ''
DECLARE @AGE AS INT
DECLARE @EMAIL AS VARCHAR(100)=''
DECLARE @MSG AS VARCHAR(500)
DECLARE @CURRENTDATE AS DATETIME = GETDATE()

DECLARE CRS CURSOR FOR
	SELECT TOP 3 NAMESURNAME,DATEDIFF(YEAR,BIRTHDATE,@CURRENTDATE) AS AGE,EMAIL
	FROM USERS
	WHERE DAY(BIRTHDATE)=DAY(@CURRENTDATE) AND MONTH(BIRTHDATE)=MONTH(@CURRENTDATE)
OPEN CRS 
FETCH NEXT FROM CRS INTO @NAMESURNAME,@AGE,@EMAIL
WHILE @@FETCH_STATUS=0
BEGIN 
SET @MSG='SAYIN '+@NAMESURNAME+', DOGUM GUNUNUZ KUYTLU OLSUN.'+CONVERT(VARCHAR,@AGE)+'. YASINIZI KUTLAR , NICE MUTLU YILLAR DILERIZ'
EXEC msdb.dbo.sp_send_dbmail @profile_name='SQLMAIL',
@SUBJECT='MUTLU YILLAR',
@BODY=@MSG,
@recipients=@EMAIL
END