/*
--PROCEDURE OLUSTURMA :(NESNE OLDUGU ICIN CREATE KOMUTUYLA OLUSTURUYORUZ)
CREATE PROCEDURE PROC_ISMI
AS --(ILE BASLAYIP)
	
	--(YAZILACAK CODLAR)

GO --(GO ILE BITIRIYORUZ)
-- ------------------------------------------------------
-- SILME ISLEMI
DROP PROCEDURE PROCEDURE_ISMI
-- ------------------------------------------------------
sp_helptext sp_ISMI -- sp hakkında BILGI EDINME
-- ------------------------------------------------------
ALTER PROCEDURE sp_ISMI 
AS
-- KODLAR
GO
*/
CREATE PROCEDURE sp_CEZALIUYE
AS

DECLARE @bugun VARCHAR(50)
SET @bugun = 'KADIN'

SELECT CUSTOMERNAME,GENDER,AGE FROM CUSTOMERS
WHERE AGE = 50 AND GENDER = @bugun 
GO

EXEC sp_CEZALIUYE
sp_helptext sp_CEZALIUYE

--DROP PROCEDURE sp_CEZALIUYE
-- ----------------------------------------------------------------------
ALTER PROCEDURE sp_CEZALIUYE
AS
DECLARE @GENDER VARCHAR(50)
SET @GENDER = 'E%'

SELECT CUSTOMERNAME,GENDER,AGE FROM CUSTOMERS
WHERE AGE = 50 AND GENDER LIKE @GENDER 
GO
EXEC sp_CEZALIUYE
sp_helptext sp_CEZALIUYE

--DROP PROCEDURE sp_CEZALIUYE

--PARAMETRE DONDUREN SP TANIMLAYALIM (OUTPUT)
--PARAMETRELİ PROCEDUR TANIMLADIK
CREATE PROCEDURE sp_ORTALIYICI
@sayi1 SMALLINT,--NULL OLMAK ZORUNDA YA DA DEFAULT DEGER
@sayi2 SMALLINT,--NULL OLMAK ZORUNDA YA DA DEFAULT DEGER
@sayi3 SMALLINT,--NULL OLMAK ZORUNDA YA DA DEFAULT DEGER
@sayi4 SMALLINT,--NULL OLMAK ZORUNDA YA DA DEFAULT DEGER
@sayi5 SMALLINT,--NULL OLMAK ZORUNDA YA DA DEFAULT DEGER
@SONUC SMALLINT OUTPUT--NULL OLMAK ZORUNDA YA DA DEFAULT DEGER
AS
SELECT @SONUC = (@sayi1+@sayi2+@sayi3+@sayi4+@sayi5)/5
GO

DECLARE @TOPLAM SMALLINT =0
EXEC sp_ORTALIYICI 10,20,30,50,60,@TOPLAM
OUTPUT
SELECT 'ORTALAMA : '= @TOPLAM
GO

--RETURN ILEDE DEGER DONDUREBILIRIZ OUTPUT DISINDA RETURN(-1 İLE -99 ARASINDAKI DEGERLERI DONDURMEZ CUNKU BUNLAR PROGRAM HATA KODLARIDIR)
CREATE PROCEDURE sp_TOPLAYICI

@TOPLANAN1 SMALLINT,
@TOPLANAN2 SMALLINT,
@TOPLAM SMALLINT = 0
AS
SELECT @TOPLAM = @TOPLANAN1+@TOPLANAN2
RETURN @TOPLAM
GO
--DROP PROCEDURE sp_TOPLAYICI
-- --------------------------------------------- RETURN PROCEDURE CAGRMA
DECLARE @TOPLAMLAR SMALLINT = 0
EXEC @TOPLAMLAR = sp_TOPLAYICI 1,11
SELECT 'SONUC = ' AS SONUC,@TOPLAMLAR AS TOPLAM



