--- HESAPLAR ARASI TRANSFER EFT HAVALE GIBI
CREATE PROCEDURE sp_PROC
@GONDEREN_ID INT,
@ALACAKLI_ID INT,
@PARAMIKRATI SMALLINT
AS
IF (SELECT AGE FROM CUSTOMERS WHERE ID = @GONDEREN_ID) > @PARAMIKRATI
BEGIN
	UPDATE CUSTOMERS SET AGE = AGE - @PARAMIKRATI WHERE ID = @GONDEREN_ID 

	UPDATE CUSTOMERS SET AGE = AGE + @PARAMIKRATI WHERE ID = @ALACAKLI_ID 
END
ELSE
BEGIN
	PRINT 'PARA YETERLI DEGIL'
END
GO
--DROP  PROCEDURE sp_PROC
EXEC sp_PROC @ALACAKLI_ID=100,@PARAMIKRATI=20,@GONDEREN_ID=200 -- PARAMETRE ISIMLERIYLE BIRLIKTE VERDIKMI SIRALAMA ONEMLI OLMUYOR
SELECT * FROM CUSTOMERS

-- ------------------------------------------------------------------------
CREATE PROCEDURE hesap_art_azl
@hesap_no INT,
@para_değeri INT,
@işlem_tipi INT
AS
IF @işlem_tipi = 1
BEGIN
UPDATE CUSTOMERS SET HESAPNO +=  @para_değeri WHERE ID = @hesap_no
END
ELSE
BEGIN
UPDATE CUSTOMERS SET HESAPNO -=  @para_değeri WHERE ID = @hesap_no
END
GO
EXEC hesap_art_azl 1,150,1
SELECT * FROM CUSTOMERS WHERE ID=1

-- -------------------------------------------------------------------------------------------
--TABLODAN COLUMN SILME
/*ALTER TABLE Customers
DROP COLUMN ContactName;*/
/*ALTER TABLE CUSTOMERS
DROP COLUMN HESAPNO
SELECT * FROM CUSTOMERS*/
-- --------------------------------------------------------------------------------------------
--KAYIT YAPAN PROCEDURE
CREATE PROCEDURE sp_EKLEME5

@CUSTOMERNAME varchar(100), 
@CITY varchar(50) ,
@BIRTHDATE date, 
@DISTRICT varchar(50), 
@GENDER varchar(10), 
@NATION varchar(50), 
@AGE int
AS
INSERT INTO  CUSTOMERS
([CUSTOMERNAME],[CITY], [BIRTHDATE], [DISTRICT], [GENDER], [NATION], [AGE]) 
VALUES(@CUSTOMERNAME,@CITY,@BIRTHDATE,@DISTRICT,@GENDER,@NATION,@AGE)
GO
-- -------------------------------------------------------------------------------------
EXEC sp_EKLEME5 'EMİRHaAN ÇİFCİ','SİVAS','2000-09-03','Pazar / SİVAS',ERKEK,NULL,20
SELECT * FROM CUSTOMERS WHERE CUSTOMERNAME='EMİRHaAN ÇİFCİ'
-- -------------------------------------------------------------------------------------
--UPDATE VE INSERT YAPAN PROCEDURE
CREATE PROCEDURE sp_EKLEME2
@sp_ID INT,
@CUSTOMERNAME varchar(100), 
@CITY varchar(50) ,
@BIRTHDATE date, 
@DISTRICT varchar(50), 
@GENDER varchar(10), 
@NATION varchar(50), 
@AGE int
AS
IF EXISTS(SELECT * FROM CUSTOMERS AS C WHERE C.ID = @sp_ID)  
BEGIN
UPDATE CUSTOMERS SET CUSTOMERNAME = @CUSTOMERNAME,CITY=@CITY, [BIRTHDATE]=@BIRTHDATE, [DISTRICT]=@DISTRICT, [GENDER]=@GENDER, [NATION]=@NATION, [AGE]=@AGE WHERE ID=@sp_ID
END
ELSE
BEGIN
INSERT INTO  CUSTOMERS
([CUSTOMERNAME],[CITY], [BIRTHDATE], [DISTRICT], [GENDER], [NATION], [AGE]) 
VALUES(@CUSTOMERNAME,@CITY,@BIRTHDATE,@DISTRICT,@GENDER,@NATION,@AGE)
END

GO
-- ------
EXEC sp_EKLEME2 1003,'EMIRH ','GERMANNNNN','2001-09-03','SUNDAY / SIVAS','MAN',NULL,20
SELECT * FROM CUSTOMERS WHERE CUSTOMERNAME='EMIRHAN'

--ILK HARDE GORE ISIMLERI GETIREN PROC
CREATE PROCEDURE ilk_HARF
@harf VARCHAR(50)='A%'
AS
SELECT * FROM CUSTOMERS WHERE CUSTOMERNAME LIKE @harf
GO
EXEC ilk_HARF '%RH%'
-- ----------------------------------------------------------------
--ISMI 5 SOYISMI 10 KARAKTERDEN OLAN CUSTOMERSLAR
CREATE PROC bes_ON
@AD VARCHAR(20) = '__________',
@SOYAD VARCHAR(20) = '__________'
AS
SELECT * FROM CUSTOMERS WHERE CUSTOMERNAME LIKE @AD AND CITY LIKE @SOYAD
GO
--DROP PROCEDURE bes_ON
EXEC bes_ON 
-- ----------------------------------------------------------------------------
--ID SI 0 İLE 5 OLAN CUSTOMERLARI YASLARINI BIR ARTTIR
CREATE PROCEDURE bir_ARTTIR
@customers_NAMR VARCHAR(20)='[M-P]_________'
AS
UPDATE CUSTOMERS SET AGE += 1 WHERE CUSTOMERNAME LIKE @customers_NAMR 
GO
DROP PROCEDURE bir_ARTTIR
EXEC bir_ARTTIR
SELECT * FROM CUSTOMERS WHERE CUSTOMERNAME LIKE '[M-P]_________'
-- ------------------------------------------------------------------------------------