
SET STATISTICS IO ON  -- NE KADAR OKUMA YAPTIGINI SOYLER

SELECT * FROM [dbo].[CUSTOMERS] WHERE TCNO = '83456324116'

SP_SPACEUSED CUSTOMERS -- TABLONUN BILGILERINI, BOYUTUNU GETIRIR

-------------------------------------------------------------------------
--INDEX OLUSTURMA

CREATE NONCLUSTERED INDEX IX1 ON CUSTOMERS
(
	NAMESURNAME
)



--INCLUDED COLUMN