SELECT IOTYPE,SUM(AMOUNT) AS GIRENURUNSAYISI,COUNT(IOTYPE) GERCEKLESENGIRISSAYISI FROM ITEMTRANSACTIONS WHERE ITEMID = 1
GROUP BY IOTYPE


SET STATISTICS IO ON
SELECT 
ID,
(SELECT SUM(AMOUNT) FROM ITEMTRANSACTIONS WHERE ITEMID=ITM.ID AND IOTYPE = 1)
-(SELECT SUM(AMOUNT) FROM ITEMTRANSACTIONS WHERE ITEMID=ITM.ID AND IOTYPE = 2) AS STOKSAYISI
FROM ITEMS AS ITM
ORDER BY ID

--STOCK TABLASI OLUSTURALIM VE USTEKI SORGUNUN YAVASLIGINI GIDERELIM
SELECT * FROM STOCK
