--TRUNCATE TABLE ITEMTRANSACTIONS

--UPDATE STOCK SET STOCK = 0

SELECT * FROM ITEMTRANSACTIONS
SELECT * FROM STOCK

--SIMDI TRIGGERMIZI YAZALIM ITEMTRANSACTIONS EKLEME OLDUGUNDA STOCK TABLOSUDA ETKILENSIN

CREATE TRIGGER TRG_TRANSACTIONS_INSERT
ON ITEMTRANSACTIONS
AFTER INSERT
AS
BEGIN
	DECLARE @ITEMID AS INT
	DECLARE @AMOUNT AS INT
	DECLARE @IOTYPE AS SMALLINT
	
	SELECT @ITEMID=ITEMID , @AMOUNT=AMOUNT , @IOTYPE=IOTYPE FROM inserted

	IF @IOTYPE = 1
		UPDATE STOCK SET STOCK = STOCK + @AMOUNT WHERE ITEMID = @ITEMID
	ELSE IF @IOTYPE = 2
		UPDATE STOCK SET STOCK = STOCK - @AMOUNT WHERE ITEMID = @ITEMID
END
GO

--ONCE TABLOYU TEMIZLIYELIM

--TRUNCATE TABLE ITEMTRANSACTIONS
--UPDATE STOCK SET STOCK = 0

--SELECT * FROM ITEMTRANSACTIONS
--SELECT * FROM STOCK WHERE STOCK <> 0

--SCRIPTIMIZI CALISTIRALIM  10-)TRIGGER_TABLE

--OKUNAN PAGE SAYISINA BAK
SELECT * FROM ITEMTRANSACTIONS

SELECT * FROM STOCK