CREATE TRIGGER TRG_TRANSACTIONS_DELETE
ON ITEMTRANSACTIONS
AFTER DELETE
AS
BEGIN
	DECLARE @ITEMID AS INT
	DECLARE @AMOUNT AS INT
	DECLARE @IOTYPE AS SMALLINT
	
	SELECT @ITEMID=ITEMID , @AMOUNT=AMOUNT , @IOTYPE=IOTYPE FROM DELETED

	IF @IOTYPE = 1
		UPDATE STOCK SET STOCK = STOCK - @AMOUNT WHERE ITEMID = @ITEMID
	ELSE IF @IOTYPE = 2
		UPDATE STOCK SET STOCK = STOCK + @AMOUNT WHERE ITEMID = @ITEMID

END

--KAYIT SILELIM VE OLUSAN DURUMU INCELEYELIM




SELECT * FROM ITEMTRANSACTIONS WHERE ITEMID = 5

SELECT * FROM STOCK WHERE ITEMID = 5 --STOCK 300 ,307, 302

DELETE ITEMTRANSACTIONS WHERE ID =1610