
USE HR
GO



INSERT INTO WORKERS

SELECT TOP 1000
TCNO AS WORKERCODE,NAMESURNAME AS WORKERNAME,GENDER,BIRTHDATE,TCNO,NEWID() AS WORKERBARCODE
FROM CRM2.DBO.CUSTOMERS



SELECT * FROM WORKERS
--TRUNCATE TABLE WORKERS

SELECT * FROM [dbo].[WORKERTRANSACTION]
--TRUNCATE TABLE [dbo].[WORKERTRANSACTION]

DECLARE @I INT = 1
WHILE @I<=1000
BEGIN
	EXEC [dbo].[GENERATE_WORKER_TRANSACTION] @I

	SET @I = @I+1
END

-- -------------------------------------------------------------
--BIR KISININ EN SON YAPTIGI ISLEIN TURUNU VE TARIHNI GETIRELIM

SELECT * ,
(SELECT TOP 1 IOTYPE FROM WORKERTRANSACTION  WR WHERE WR.WORKERID = W.ID ORDER BY DATE_ DESC ) SONHAREKETTURU,
(SELECT MAX(DATE_) FROM WORKERTRANSACTION  WR WHERE WR.WORKERID = W.ID ) SONHAREKETZAMANI
FROM WORKERS W WHERE ID = 1

----------------------------------------------------------------------------------------------------------------------
--YENI TABLO OLUSTURDUK VE WORKERID LERINI DOLDURALIM
INSERT INTO WORKER_LAST_TRANSACTIONS
(WORKERID)
SELECT ID FROM WORKERS
-----------------------------------------------------
SELECT * FROM WORKER_LAST_TRANSACTIONS

-- --------------------------------------------------
--TRIGGER BOLUMU

CREATE TRIGGER TRG_TRANSACTIONS_INSERT
ON [dbo].[WORKERTRANSACTIONS]
AFTER INSERT
AS
BEGIN
DECLARE @WORKERID AS INT
DECLARE @DATE AS DATETIME
DECLARE @IOTYPE AS VARCHAR(1)

	SELECT @WORKERID=WORKERID,@DATE=DATE_,@IOTYPE=IOTYPE FROM inserted

	UPDATE WORKER_LAST_TRANSACTIONS SET LASTDATE = @DATE ,LASTIOTYPE = @IOTYPE WHERE WORKERID=@WORKERID

END

EXEC [dbo].[GENERATE_WORKER_TRANSACTION] 1

SELECT TOP 1 * FROM [dbo].[WORKERTRANSACTIONS] WHERE WORKERID = 1  ORDER BY DATE_ DESC

SELECT * FROM WORKER_LAST_TRANSACTIONS 

SELECT * FROM [dbo].[WORKERTRANSACTIONS]

