
USE ETRADE
SELECT * FROM ITEMS_LOG

--UPDATE

CREATE TRIGGER TRG_ITEMS_UPDATE
ON ITEMS
AFTER UPDATE
AS
BEGIN

	INSERT INTO ITEMS_LOG([ID], [ITEMCODE], [ITEMNAME], [UNITPRICE], [CATEGORY1], [CATEGORY2], [CATEGORY3], [CATEGORY4], [BRAND], [LOG_ACTIONTYPE], [LOG_DATE], [LOG_USERNAME], [LOG_PROGRAMNAME], [LOG_HOSTNAME])
	
	SELECT [ID], [ITEMCODE], [ITEMNAME], [UNITPRICE], [CATEGORY1], [CATEGORY2], [CATEGORY3], [CATEGORY4], [BRAND],'UPDATE',GETDATE(),SUSER_NAME(), PROGRAM_NAME(),HOST_NAME()
	FROM deleted 
END


SELECT SUSER_NAME() --SQL SERVER A HANGI KULLANICIYLA BAGLANDIYSAN ONU ISMINI VERIR

SELECT PROGRAM_NAME() --SQL KULLANICININ BAGLANDIGI PROGRAMIN ADINI GETIRIR

SELECT HOST_NAME() --BAGLANAN KULLANICIN PC SININ ADI


--DELETED
CREATE TRIGGER TRG_ITEMS_DELETE
ON ITEMS
AFTER DELETE
AS
BEGIN

	INSERT INTO ITEMS_LOG([ID], [ITEMCODE], [ITEMNAME], [UNITPRICE], [CATEGORY1], [CATEGORY2], [CATEGORY3], [CATEGORY4], [BRAND], [LOG_ACTIONTYPE], [LOG_DATE], [LOG_USERNAME], [LOG_PROGRAMNAME], [LOG_HOSTNAME])
	
	SELECT [ID], [ITEMCODE], [ITEMNAME], [UNITPRICE], [CATEGORY1], [CATEGORY2], [CATEGORY3], [CATEGORY4], [BRAND],'DELETE',GETDATE(),SUSER_NAME(), PROGRAM_NAME(),HOST_NAME()
	FROM deleted 
END

--DELETE VE UPDATE I TEK SCRIPTE BIRLESTIRIYORUZ

CREATE TRIGGER TRG_ITEMS_DELETE_UPDATE
ON ITEMS
AFTER DELETE,UPDATE
AS
BEGIN

DECLARE @DELETEDCOUNT AS INT
DECLARE @INSERTEDCOUNT AS INT

SELECT @DELETEDCOUNT = COUNT(*) FROM deleted
SELECT @INSERTEDCOUNT = COUNT(*) FROM inserted
DECLARE @LOG_ACTIONTYPE AS VARCHAR(20)

IF @DELETEDCOUNT > 0 AND @INSERTEDCOUNT > 0
	SET @LOG_ACTIONTYPE = 'UPDATE'
IF @DELETEDCOUNT > 0 AND @INSERTEDCOUNT = 0
	SET @LOG_ACTIONTYPE = 'DELETE'

	INSERT INTO ITEMS_LOG([ID], [ITEMCODE], [ITEMNAME], [UNITPRICE], [CATEGORY1], [CATEGORY2], [CATEGORY3], [CATEGORY4], [BRAND], [LOG_ACTIONTYPE], [LOG_DATE], [LOG_USERNAME], [LOG_PROGRAMNAME], [LOG_HOSTNAME])
	
	SELECT [ID], [ITEMCODE], [ITEMNAME], [UNITPRICE], [CATEGORY1], [CATEGORY2], [CATEGORY3], [CATEGORY4], [BRAND],@LOG_ACTIONTYPE,GETDATE(),SUSER_NAME(), PROGRAM_NAME(),HOST_NAME()
	FROM deleted 
END

SELECT * FROM [ETRADE].[dbo].[ITEMS] WHERE ID = 16
  
  SELECT * FROM [dbo].[ITEMS_LOG]