
USE BANK
GO

--SENARYO

--AHMET OMERE 1000 TL PARA GONDERİYOR

SELECT C.CUSTOMERNAME,A.ACCOUNTNO,A.ACCOUNTNAME,A.CURRENCY,B.BALANCE FROM [dbo].[ACCOUNTBALANCE] B
INNER JOIN [dbo].[ACCOUNTS] A ON A.ID = B.ACCOUNTID
INNER JOIN CUSTOMERS C ON C.ID = A.CUSTOMERID

INNER JOIN [dbo].[MONEYTRANSACTIONS]

--ISLEMIMIZI GERCEKLESTIRELIM

INSERT INTO [dbo].[MONEYTRANSACTIONS] 
([ACCOUNTID], [TRANTYPE], [AMOUNT], [DATE_], [CURRENCY], [EFTCODE1], [EFTCODE2])

VALUES(1,2,1000,'2020-04-14 14:21:36','TL','12345678','')

UPDATE [dbo].[ACCOUNTBALANCE] SET BALANCE = BALANCE - 1000 WHERE [ACCOUNTID] = 1

INSERT INTO [dbo].[MONEYTRANSACTIONS] 
([ACCOUNTID], [TRANTYPE], [AMOUNT], [DATE_], [CURRENCY], [EFTCODE1], [EFTCODE2])

VALUES(2,1,1000,'2020-04-14 15:21:36','TL','12345678','0987654321')

UPDATE [dbo].[ACCOUNTBALANCE] SET BALANCE = BALANCE + 1000 WHERE [ACCOUNTID] = 2

SELECT * FROM CUSTOMERS 
SELECT * FROM [dbo].[MONEYTRANSACTIONS]
SELECT C.CUSTOMERNAME,A.ACCOUNTNO,A.ACCOUNTNAME,A.CURRENCY,B.BALANCE FROM [dbo].[ACCOUNTBALANCE] B
INNER JOIN [dbo].[ACCOUNTS] A ON A.ID = B.ACCOUNTID
INNER JOIN CUSTOMERS C ON C.ID = A.CUSTOMERID

--ZINCIR TAMAMLANMIS GIBI GORUNUYOR


--ZINCIRIN HERHANGIBIR YERIMDE HATA CIKINCA NE YAPACAGIZ BUNUN ICIN DEGERLERI ESKI HALINE GETIRELIM

TRUNCATE TABLE [dbo].[MONEYTRANSACTIONS]

UPDATE ACCOUNTBALANCE SET BALANCE = 1000 WHERE ID = 1

UPDATE ACCOUNTBALANCE SET BALANCE = 0 WHERE ID = 2

SELECT * FROM [dbo].[ACCOUNTBALANCE] --YAZDIGIMIZ HER SATIR TRANSACTIONDIR BIZ TRANSACTIONLARI KOD BLOGU OLARAK KULLANABILIRIZ VE ZINCIRDEKI PROBLEMI COZEBILIRIZ

-----------------------------------------------------------------------------------------------------------------------------------------------------------------

BEGIN TRAN --BEGIN TRAN ILE TRANSACTION NI BASLATIRIZ VE COMMIT TRAN VEYA ROLLBACK TRAN DIYE BITIRIRIZ

INSERT INTO [dbo].[MONEYTRANSACTIONS] 
([ACCOUNTID], [TRANTYPE], [AMOUNT], [DATE_], [CURRENCY], [EFTCODE1], [EFTCODE2])
VALUES(1,2,1000,'2020-04-14 14:21:36','TL','12345678','')

IF @@ERROR > 0 -- @@ GLOBAL DEGISKEN OLDUGUNU SOYLER @@ERROR > 0 HATA OLMUSSSA BLOGA GIR
BEGIN
	ROLLBACK TRAN
	RETURN
END

UPDATE [dbo].[ACCOUNTBALANCE] SET BALANCE = BALANCE - 1000 WHERE [ACCOUNTID] = 1

IF @@ERROR > 0 -- @@ GLOBAL DEGISKEN OLDUGUNU SOYLER @@ERROR > 0 HATA OLMUSSSA BLOGA GIR
BEGIN
	ROLLBACK TRAN
	RETURN
END

INSERT INTO [dbo].[MONEYTRANSACTIONS] 
([ACCOUNTID], [TRANTYPE], [AMOUNT], [DATE_], [CURRENCY], [EFTCODE1], [EFTCODE2])
VALUES(2,1,1000,'2020-04-14 15:21:36','TL','12345678','ABCDFG0987654321') --SISTEMI HATA VERDIRECEZ BILEREK --VE DURUM NE OLMUS GERIYE ALINMISMI BAKALIM

IF @@ERROR > 0 -- @@ GLOBAL DEGISKEN OLDUGUNU SOYLER @@ERROR > 0 HATA OLMUSSSA BLOGA GIR
BEGIN
	ROLLBACK TRAN
	RETURN
END

UPDATE [dbo].[ACCOUNTBALANCE] SET BALANCE = BALANCE + 1000 WHERE [ACCOUNTID] = 2

IF @@ERROR > 0 -- @@ GLOBAL DEGISKEN OLDUGUNU SOYLER @@ERROR > 0 HATA OLMUSSSA BLOGA GIR
BEGIN
	ROLLBACK TRAN --TRANSACTION ZINCIRI KOPTU ISLEMI TAMAMEN GERI AL
	RETURN
END

COMMIT TRAN --TRANSACTION NI TAMAMLA LDF DOSYASINDAKI KAYIRLARI MDF DOSYASINA KALICI SEKILDE YAZ

SELECT * FROM CUSTOMERS 
SELECT * FROM [dbo].[MONEYTRANSACTIONS]
SELECT C.CUSTOMERNAME,A.ACCOUNTNO,A.ACCOUNTNAME,A.CURRENCY,B.BALANCE FROM [dbo].[ACCOUNTBALANCE] B
INNER JOIN [dbo].[ACCOUNTS] A ON A.ID = B.ACCOUNTID
INNER JOIN CUSTOMERS C ON C.ID = A.CUSTOMERID

--GOROULDUGU GIBI ISLEM OLMAMIS 

-----------------------------------------------------------------------------------------------------------------------------------------------------------------

BEGIN TRAN --BEGIN TRAN ILE TRANSACTION NI BASLATIRIZ VE COMMIT TRAN VEYA ROLLBACK TRAN DIYE BITIRIRIZ

INSERT INTO [dbo].[MONEYTRANSACTIONS] 
([ACCOUNTID], [TRANTYPE], [AMOUNT], [DATE_], [CURRENCY], [EFTCODE1], [EFTCODE2])
VALUES(1,2,1000,'2020-04-14 14:21:36','TL','12345678','')

IF @@ERROR > 0 -- @@ GLOBAL DEGISKEN OLDUGUNU SOYLER @@ERROR > 0 HATA OLMUSSSA BLOGA GIR
BEGIN
	ROLLBACK TRAN
	RETURN
END

UPDATE [dbo].[ACCOUNTBALANCE] SET BALANCE = BALANCE - 1000 WHERE [ACCOUNTID] = 1

IF @@ERROR > 0 -- @@ GLOBAL DEGISKEN OLDUGUNU SOYLER @@ERROR > 0 HATA OLMUSSSA BLOGA GIR
BEGIN
	ROLLBACK TRAN
	RETURN
END

INSERT INTO [dbo].[MONEYTRANSACTIONS] 
([ACCOUNTID], [TRANTYPE], [AMOUNT], [DATE_], [CURRENCY], [EFTCODE1], [EFTCODE2])
VALUES(2,1,1000,'2020-04-14 15:21:36','TL','12345678','0987654321') --SISTEMI HATA VERDIRECEZ BILEREK (SIMDI ISE HATA VERDIRMEYECEGIZ)--VE DURUM NE OLMUS GERIYE ALINMISMI BAKALIM

IF @@ERROR > 0 -- @@ GLOBAL DEGISKEN OLDUGUNU SOYLER @@ERROR > 0 HATA OLMUSSSA BLOGA GIR
BEGIN
	ROLLBACK TRAN
	RETURN
END

UPDATE [dbo].[ACCOUNTBALANCE] SET BALANCE = BALANCE + 1000 WHERE [ACCOUNTID] = 2

IF @@ERROR > 0 -- @@ GLOBAL DEGISKEN OLDUGUNU SOYLER @@ERROR > 0 HATA OLMUSSSA BLOGA GIR
BEGIN
	ROLLBACK TRAN --TRANSACTION ZINCIRI KOPTU ISLEMI TAMAMEN GERI AL
	RETURN
END

COMMIT TRAN --TRANSACTION NI TAMAMLA LDF DOSYASINDAKI KAYIRLARI MDF DOSYASINA KALICI SEKILDE YAZ

SELECT * FROM CUSTOMERS 
SELECT * FROM [dbo].[MONEYTRANSACTIONS]
SELECT C.CUSTOMERNAME,A.ACCOUNTNO,A.ACCOUNTNAME,A.CURRENCY,B.BALANCE FROM [dbo].[ACCOUNTBALANCE] B
INNER JOIN [dbo].[ACCOUNTS] A ON A.ID = B.ACCOUNTID
INNER JOIN CUSTOMERS C ON C.ID = A.CUSTOMERID

--(BU SEFER ISLEM GERCEKLESTI)
