USE ETRADE
GO

SELECT * FROM ITEMS

SELECT * FROM ITEMS_LOG


SELECT * FROM ITEMS WHERE ID = 3

BEGIN TRAN 
UPDATE ITEMS SET UNITPRICE = 60 WHERE ID = 3 --TRANSACTION NI ACTIK VE KAPATMADIK VE ONCEKI DERLERDE YAZDIGIMIZ TRIGGERIMIZDA CALISTI

SELECT * FROM ITEMS_LOG WHERE ID = 3 --TRIGGERIMIZIN DEGISIKLIKLERI EKLEDIGI TABLE

--TRANSACTION NI ACTIK VE KAPATMADIK MDF YANI CANLI DOSYADA DEGIL LDFLOG DOSYASINDA BIZ ROLLBACK YAPARSAK BU DURMLAR GERCEKLESMEZ


--TRANSACTION ACIK OLDUGUNDAN BIR BASKA SESSIONDAN BIR KULLANICI SORGULAMA YAPARSA BASIT SORGULAMA BILE OLSA DEGER DONMEZ CUNKU TRANSACTION NI KAPAMADIK


SELECT * FROM ITEMS WHERE ID = 3 -- BASKA SESSIONDA BUNU DENE

ROLLBACK -- ISLEI GERI ALALIM

--TRIGGERLAR TRANSACTIONLARIN BIR PARCASIDIR

-- BASKA SESSIONDA BUNU DENE CALISMAYACAGI BUNUN COZUMU LOCLARA TAKILMADAN CALISTIRMAMIZ LAZIM

SELECT * FROM ITEMS WITH (NOLOCK) -- LOCK A TAKILMADAN CEK

DBCC OPENTRAN --ACIK TRANSACTION VARMI


SELECT * FROM ITEMS
WITH (NOLOCK)
WHERE ID = 3
--TRANSACTION CALISIYORKEN ESKI FIYATIMI GORURUM YENI FIYATIMI GUNCELLENMIS HALINI GOSTERIR






