CREATE VIEW VW_SIPARIS_DETAYLI
AS
SELECT
U.USERNAME_ KULLANICIADI,
U.NAMESURNAME ADSOYAD,
U.TELNR1 TELEFON1,
U.TELNR2 TELEFON2,
C.COUNTRY ULKE,
CT.CITY SEHIR,
T.TOWN ILCE,
A.ADDRESSTEXT ACIKADRES,
O.ID SIPARISID,
ITM.ITEMCODE URUNKODU,
ITM.ITEMNAME URUNADI,
ITM.BRAND MARKA,
ITM.CATEGORY1 KATEGORI1,
ITM.CATEGORY2 KATEGORI2,
ITM.CATEGORY3 KATEGORI3,
ITM.CATEGORY4 KATEGORI4,
OD.AMOUNT MIKTAR,
OD.UNITPRICE BIRIMFIYAT,
OD.LINETOTAL SATIRTOPLAMI,

CONVERT(DATE,O.DATE_) AS TARIH, --CONVERT BIR VERI TIPINI BASKA VERI TIPINE DONUSTURUR
CONVERT(TIME,O.DATE_) SIPARISZAMANI,
DATEPART(YEAR,O.DATE_) AS YIL,
DBO.FIND_MONTH(O.DATE_) AS AY,
dbo.FIND_DAY(O.DATE_)AS HAFTANINGUNU
FROM 
ORDERDETAILS OD
INNER JOIN ORDERS O ON OD.ORDERID = O.ID
INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID
INNER JOIN USERS U ON U.ID = O.USERID
INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
INNER JOIN COUNTRIES C ON C.ID=A.COUNTRYID
INNER JOIN CITIES CT ON CT.ID = A.CITYID
INNER JOIN TOWNS T ON T.ID=A.TOWNID
INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
GO

SELECT * FROM VW_SIPARIS_DETAYLI

-- EN COK SATAN 10 KATEGORI

CREATE VIEW VW_TOP10_KATEGORI
AS
SELECT TOP 10 KATEGORI1,SUM(SATIRTOPLAMI) AS TOPLAMTUTAR
FROM VW_SIPARIS_DETAYLI 
GROUP BY KATEGORI1
ORDER BY SUM(SATIRTOPLAMI) DESC
GO

SELECT * FROM VW_TOP10_KATEGORI
------------------------------------------------------------
CREATE VIEW VW_MAGAZA_ANALIZI
AS
SELECT SEHIR,SUM(SATIRTOPLAMI) AS TOPLAMTUTAR
FROM VW_SIPARIS_DETAYLI 
GROUP BY SEHIR

GO

SELECT * FROM VW_MAGAZA_ANALIZI

-----------------------------------------------------

CREATE VIEW VW_TOP_1000_MUSTERI_LISTESI
AS
SELECT TOP 1000 KULLANICIADI,ADSOYAD,SEHIR,ILCE,ACIKADRES,TELEFON1,TELEFON2,SUM(SATIRTOPLAMI) AS TOPLAMTUTAR
FROM VW_SIPARIS_DETAYLI 
GROUP BY KULLANICIADI,ADSOYAD,SEHIR,ILCE,ACIKADRES,TELEFON1,TELEFON2
ORDER BY SUM(SATIRTOPLAMI) DESC

SELECT * FROM VW_TOP_1000_MUSTERI_LISTESI

-----------------------------------------------------

SELECT SEHIR,HAFTANINGUNU,SUM(SATIRTOPLAMI)
FROM VW_SIPARIS_DETAYLI
GROUP BY SEHIR,HAFTANINGUNU