
ALTER PROC SP_WORKER_INOUT
@WORKERBARCODE AS VARCHAR(50),
@DATE AS DATETIME,
@IOTYPE AS VARCHAR(1),
@GATEID AS INT
AS
BEGIN
	
DECLARE @WORKERNAME AS VARCHAR(100)
DECLARE @WORKERID AS INT

SELECT @WORKERNAME = WORKERNAME,@WORKERID = ID FROM WORKERS
WHERE WORKERBARCODE = @WORKERBARCODE

	IF @WORKERID IS NULL
	BEGIN

		RAISERROR('OKUTULAN KAR GEÇERSİZDİR',16,1)
		RETURN
		
	END

DECLARE @LASTIO AS VARCHAR(1)

SELECT TOP 1 @LASTIO = IOTYPE FROM WORKERTRANSACTION
WHERE WORKERID=1 AND DATE_ <= CONVERT(DATE,GETDATE())
ORDER BY DATE_ DESC

	IF @LASTIO = @IOTYPE
	BEGIN
		IF @IOTYPE='G'
		BEGIN
			RAISERROR('ZATEN İÇERİDE GORUNUYORSUNUZ, GİRİŞ YAPAMAZSINIZ',16,1)
			RETURN
		END
		IF @IOTYPE='C'
		BEGIN
			RAISERROR('ZATEN DIŞARIDA GORUNUYORSUNUZ, ÇIKIŞ YAPAMAZSINIZ',16,1)
			RETURN
		END
	END

INSERT INTO WORKERTRANSACTION ([WORKERID], [DATE_], [IOTYPE], [GATEID])
VALUES (@WORKERID, @DATE, @IOTYPE, @GATEID)

SELECT @WORKERNAME AS WORKNAME,@DATE AS DATE_,@IOTYPE AS IOTYPE,@GATEID AS GATEID

END
GO

--------------------------------------------------------------------------
TRUNCATE TABLE [dbo].[WORKERTRANSACTION]

SELECT * FROM [dbo].[WORKERTRANSACTION]

--------------------------------------------------------------------
--KAYIT EKLIYELIM

EXEC SP_WORKER_INOUT @DATE='2020-04-12 17:36:48',
@WORKERBARCODE = 'A1330622-D4BD-4720-ADFE-109173B66064',
@IOTYPE='C',
@GATEID=7


SELECT * FROM [dbo].[WORKERTRANSACTION]

--PROCEDURLERIN ISTATISTIKLERINI GOSTEREN CODE

SELECT * FROM sys.dm_exec_procedure_stats


--etrade database procedure istatistikleri


SELECT 
DB_NAME(database_id) AS DBNAME,
OBJECT_NAME(object_id) AS PROCNAME,
* FROM sys.dm_exec_procedure_stats WHERE DB_NAME(database_id)='HR'

EXEC SP_WORKER_INOUT @DATE='2020-04-12 18:36:48',
@WORKERBARCODE = 'A1330622-D4BD-4720-ADFE-109173B66064',
@IOTYPE='G',
@GATEID=7

