--select * from WORKERS

--INSERT INTO WORKERS(WORKERCODE,WORKERNAME,GENDER,BIRTHDATE,TCNO,WORKERBARCODE)
--SELECT TOP 1000
--TCNO AS WORKERCODE,NAMESURNAME AS WORKERNAME,GENDER,BIRTHDATE,TCNO,NEWID() AS WORKERBARCODE
--FROM CRM2.DBO.CUSTOMERS


ALTER TRIGGER [TRG_TRANSACTIOIN_INSERT]
ON WORKERTRANSACTIONS
AFTER INSERT
AS
BEGIN 
	DECLARE @IOTYPE AS VARCHAR(1)
	DECLARE @WORKERID AS INT
	DECLARE @DATE_ AS DATETIME
	SELECT @IOTYPE=IOTYPE,@WORKERID=WORKERID,@DATE_=DATE_ FROM inserted 

	UPDATE WORKER_LAST_TRANSACTIONS SET LASTIOTYPE =@IOTYPE,LASTDATE=@DATE_ WHERE WORKERID=@WORKERID 

END