--View Konusu


--Rapor Çekelim 

--VIEW OLUSTURMA CREATE ,UPDATE ETME ALTER , SILME DROP

CREATE VIEW VWORDERS 
AS
SELECT 
U.USERNAME_ KULLANICIADI,U.NAMESURNAME ADSOYAD,C.COUNTRY ULKE,CT.CITY SEHÝR,T.TOWN ILCE,A.ADDRESSTEXT ACIKADRES,
O.ID SIPARISID,O.DATE_ SIPARISTARIHI,ITM.ITEMCODE URUNKODU,ITM.ITEMNAME URUNADI,ITM.BRAND MARKA,
OD.AMOUNT MIKTAR,OD.UNITPRICE BIRIMFIYAT,OD.LINETOTAL SATIRTOPLAMI
FROM 
ORDERDETAILS OD 
INNER JOIN ORDERS O ON OD.ORDERID=O.ID
INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID
INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
INNER JOIN COUNTRIES C ON C.ID = A.COUNTRYID
INNER JOIN CITIES CT ON CT.ID = A.CITYID
INNER JOIN TOWNS T ON T.ID = A.TOWNID
INNER JOIN PAYMENTS P ON P.ORDERID=P.ID
WHERE U.USERNAME_ = 'Z_DALAMANLI'



SELECT SEHÝR,SUM(SATIRTOPLAMI),COUNT(*) FROM VWORDERS GROUP BY SEHÝR