--Yoneticiler aylara gore satýs raporlarýný istedi , View Lar Raporlama için kullanýlýr 
ALTER View  VW_AYLARA_GORE_SATISLAR
AS
SELECT
DATEPART(YEAR,O.DATE_) YIL,
CASE 
WHEN DATEPART(MONTH,O.DATE_) = 1 THEN 'OCAK'
WHEN DATEPART(MONTH,O.DATE_) = 2 THEN 'ÞUBAT'
WHEN DATEPART(MONTH,O.DATE_) = 3 THEN 'MART'
WHEN DATEPART(MONTH,O.DATE_) = 4 THEN 'NÝSAN'
WHEN DATEPART(MONTH,O.DATE_) = 5 THEN 'MAYIS'
WHEN DATEPART(MONTH,O.DATE_) = 6 THEN 'HAZÝRAN'
WHEN DATEPART(MONTH,O.DATE_) = 7 THEN 'TEMMUZ'
WHEN DATEPART(MONTH,O.DATE_) = 8 THEN 'AÐUSTOS'
WHEN DATEPART(MONTH,O.DATE_) = 9 THEN 'EYLÜL'
WHEN DATEPART(MONTH,O.DATE_) = 10 THEN 'EKÝM'
WHEN DATEPART(MONTH,O.DATE_) = 11 THEN 'KASIM'
WHEN DATEPART(MONTH,O.DATE_) = 12 THEN 'ARALIK'

END AS AY,
SUM(AMOUNT) TOPLAMMITAR , SUM(LINETOTAL) TOPLAMTUTAR , COUNT(OD.ID) URUNSAYISI,
COUNT(DISTINCT O.ID) AS MUSTERISAYISI
FROM 
ORDERDETAILS OD 
INNER JOIN ORDERS O ON OD.ORDERID=O.ID
INNER JOIN ITEMS ITM ON ITM.ID = OD.ITEMID
INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID = O.ADDRESSID
INNER JOIN COUNTRIES C ON C.ID = A.COUNTRYID
INNER JOIN CITIES CT ON CT.ID = A.CITYID
INNER JOIN TOWNS T ON T.ID = A.TOWNID
INNER JOIN PAYMENTS P ON P.ORDERID=P.ID

GROUP BY DATEPART(YEAR,O.DATE_) ,DATEPART(MONTH,O.DATE_) 

ORDER BY DATEPART(YEAR,O.DATE_)


SELECT * FROM VW_AYLARA_GORE_SATISLAR