/*
-- ESKI TEKNIK 
SELECT A.KOLON1,A.KOLON2,B.KOLON3,B.KOLON4 
FROM TABLO1 A,TABLO2 B WHERE A.PK_KOLON=B.FK_KOLON

-- YENI TEKNIK
SELECT A.KOLON1,A.KOLON2,B.KOLON3,B.KOLON4 
FROM TABLO1 A --JOIN BIRLESTIR DEMEK
JOIN TABLO2 B ON A.PK_KOLON=B.FK_KOLON --ON DAN SONRA HANGI SARTA GORE BELIRLIYECEGIMIZI SOYLERIZ


*/
SELECT U.NAMESURNAME,U.EMAIL,A.ADDRESSTEXT,C.COUNTRY,CT.CITY,T.TOWN,D.DISTRICT FROM USERS U
JOIN ADDRESS A ON A.USERID=U.ID 
JOIN COUNTRYS C ON C.ID=A.COUNTRYID
JOIN CITIES CT ON CT.ID=A.CITYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID

-- -----------------------------------------------------------------------------------------
SELECT CT.CITY,COUNT(U.ID) AS KULLANICISAYISI FROM USERS U
JOIN ADDRESS A ON A.USERID=U.ID 
JOIN COUNTRYS C ON C.ID=A.COUNTRYID
JOIN CITIES CT ON CT.ID=A.CITYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRICTS D ON D.ID=A.DISTRICTID--DIREK JOIN YAZARSAK VERI TABANI DEFAULT OLARAK INNER JOIN OLARAK ALGILAR
GROUP BY CT.CITY

