--SELECT KOLONADI1,KOLONADI2,KOLONADI3 ...
--FROM TABLO_ADI 
--WHERE <SARTLAR>
USE ETRADE
GO
SELECT * FROM CUSTOMERS
--KOLON ISIMLERINI AYRI YAZMIYORUZ VE _ DISINDA HERHANGİ BIR YABANCI KARAKTTER KULLANMIYORUZ VE TURKCE KARAKTERDE KULLANMIYORUZ