--BIR MILYON KOMUTTAN 200 TANESINI GORMEK ISTIYORSAK BU KOMUYT KULLANILIR
/*
SELECT TOP N
KOLON1,KOLON2,KOLON3
FROM TABLOADI
WHERE <SARTLAR>

*/

SELECT TOP 100 -- ILK YUZ SATIR
* FROM CUSTOMERS
ORDER BY CUSTOMERNAME

SELECT TOP 20 PERCENT--PERCENT(YUZDE) -- YUZDE YIRMISINI GETIR
* FROM CUSTOMERS
ORDER BY CUSTOMERNAME