-- GROUP BY KULLANIMI
/*
SELECT KOLON1,KOLON2...
SUM(PRICE),
COUNT(ID),
MIN(PRICE),
MAX(PRICE),
AVG(PRICE)
FROM TABLOADI
GROUP BY KOLON1,KOLON2...


*/
--SELECT * FROM CUSTOMERS
SELECT CITY,
SUM(TOTALPRICE) AS TOTALPRICE,
COUNT(ID) AS ROWCOUNT_,
MIN(TOTALPRICE) AS  MINPRICE,
MAX(TOTALPRICE) AS  MAXPRICE,
AVG(TOTALPRICE) AS  AVEGRATE
FROM SALES
GROUP BY CITY
ORDER BY SUM(TOTALPRICE) DESC

-- ------------------------------------------------------

--CITY TABLOSUNA GORE TOTOLPRICE TOPLAMININ EN YUKSEK OLAN ILK 10 DEGERI SIRALA
SELECT TOP 10 PERCENT
CITY,
SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES
GROUP BY CITY
ORDER BY SUM(TOTALPRICE) DESC

