--BİR MAGAZANIN GUN BAZLI SATIS RAKAMLARINI GETIRME
--CONVERT(OLUSANVERİTİPİ,DEGİSTİRİLCEKVERİTİPİ)
SELECT CONVERT(DATE,DATE_) AS DATE2,*
FROM SALES WHERE CITY='ANKARA' 
ORDER BY DATE_
--- -----------------------------------------------------------
UPDATE SALES SET DATE2=CONVERT(DATE,DATE_)

SELECT DATE2,
SUM(TOTALPRICE) AS TOTALPRICE
FROM SALES WHERE CITY='ANKARA'
GROUP BY DATE2
ORDER BY DATE2



