--AGGEREGATE FUNCTION WHERE SARTINDA 
--KULLANMAK ISTIYORSAK GROUP BY DAN SONRA HAVING IFADESIYLE KULLANILIR

SELECT CITY,
SUM(TOTALPRICE) AS TOTALPRICE,
COUNT(DISTINCT CUSTOMERNAME ) AS TOTALCUSTOMERS
FROM SALES
GROUP BY CITY
HAVING COUNT(DISTINCT CUSTOMERNAME)>500
ORDER BY SUM(TOTALPRICE) DESC