--LEFT JOIN 
SELECT U.ID,U.USERNAME,A.ADDRESSTEX 
FROM USERS U LEFT JOIN ADDRESS A ON A.ID=U.ID --USERS TABLOSUNUN TAMAMINI GETIR(X-Y)


SELECT U.ID,U.USERNAME,A.ADDRESSTEX 
FROM USERS U RIGHT JOIN ADDRESS A ON A.ID=U.ID --ADDRESS TABLOSUNUN TAMAMINI GETIR(Y-X)

SELECT U.ID,U.USERNAME,A.ADDRESSTEX 
FROM USERS U FULL JOIN ADDRESS A ON A.ID=U.ID --IKITABLONUN TAMANINI GETIR(XUY) TABLOSUNUN TAMAMINI GETIR
