--UPDATE TABLOADI
--SET COLUM1=VALUE1,COLUM2=VALUE2,COLUM3=VALUE3,...
--WHERE <ŞARTLAR>

UPDATE CUSTOMERS
SET NATION='US'
--WHERE KOSULU OLMADIGINDAN TUM TABLO ETKILENIR


--SELECT SORGULUYALIM
SELECT * FROM CUSTOMERS

