--DELETE KOMUTU TABLODAK? VER?LER? S?LER VE TABLOYU ?LK HAL?NE GET?RMEZ YAN? ID DEGER? KALDIGI YERDEN DEVAM EDER

--DELETE
--FROM TABLOADI
--WHERE <SARTLAR>


DELETE
FROM CUSTOMERS

--SELECT SORGUSU CALISTIRALIM
SELECT * FROM CUSTOMERS
--VER? EKLEYELIM
INSERT INTO CUSTOMERS(CUSTOMERNAME,CITY,DISTRICT,BIRTHDATE,GENDER)
VALUES ('Volkan ÇEK?P','Bart?n','Kuruca?ile','1997-10-24 00:00:00.000','E')
--TEKRAR SELECT SORGUSU CALISTIRALIM
SELECT * FROM CUSTOMERS
--VE GORULDUGU GIBI ID DEGERI KALDIGI YERDEN DEVAM ETTI BUNU NASIL COZERIZ BIR SONRAKI BOLUMDE (TRUNCATE :) IPUCU OLSUN )
