--TRUNCATE KOMUTU TABLOYU ILK OLUSTURDUGUMUZ HALE GETIREN KOMUT YANI BİR ID DEGERI OTAMATIK ARTIYORSA
--VE BIZ KALDIGI YERDEN DEGILDE TABLONUN ILK HALINDEN YANI 1 DE BASLATMAK ISTERSEK TRUNCATE KOMUTUNU KULLANIRIZ 
--HATIRLARSANIZ BI ONCEKI BOLUMDE DELETE KOMUTU BUNU YAPAMIYORDU

--YAPISI

--TRUNCATE TABLO TABLOADI

TRUNCATE TABLE CUSTOMERS
--SELECT SORGULATALIM TABLO ESKI HALINDE GELMISMI YANI ICI BOSMU
SELECT * FROM CUSTOMERS--GORULDUGU GIBI TABLO BOS
--ELEMAN EKLIYELIM ID DEGERI 1 DENMI BASLIYOR YANI TABLONUN ILK HALIMI
INSERT INTO CUSTOMERS(CUSTOMERNAME,CITY,DISTRICT,BIRTHDATE,GENDER) VALUES ('Serhat GÜNDOĞAN','Rize','Pazar / Rize','1966-02-03 00:00:00.000','E')
--SELECT SORGULATALIM
SELECT * FROM CUSTOMERS--GORULDUGU ID DEGERI EN BASA DONDU :)
