--'='       : ESITTIR (WHERE CITY="ISTANBUL",WHERE CUSTOMERSNAME="EMIRHAN")
--'<>'      : ESIT DEGILDIR (WHERE CITY<>'ISTANBUL' OR WHERE NOT CITY='ISTANBUL')
--'>'       : BUYUKTUR (WHERE BIRTDAY>'19900101') --(YEAR/MONTH/DAY)
--'<'       : KUCUKTUR (WHERE BIRTDAY<'19900101')
--'>='      : BUYUK YA DA ESITTIR (WHERE BIRTDAY>='19900101')
--'<='      : KUCUK YA DA ESITTIR (WHERE BIRTDAY<='19900101')
--'BETWEEN' : ARASINDADIR (WHERE BETWEEN '19900101' AND '19981231' ) OR (WHERE BETWEEN 22 AND 30)--BETWEEN KOMUTU BUYUK ESITTIR VE KUCUK ESITTIR OLARAK TANIMLIYA BILIRIZ NE DEMEK ISTIYORUM ARALIGI BELIRLEDIGIMIZ DEGERLERIDE GETIRI
--'LIKE'    : ILE BASLAR, ILE BITER, ICERIR --ILE BASLAR (WHERE CUSTOMERNAME LIKE 'ALI%') --ILE BITER (WHERE CUSTOMERNAME LIKE '%ALP') --ICERIR (WHERE CUSTOMERNAME LIKE '%ALAN%')
--'IN'      : ICINDEDIR (WHERE CITY IN('ISTANBUL','ANKARA','BURSA')) --CITY ISTANBUL ANKARA BURSA OLAN BUTUN SATIRLARI GETIR
--'NOT      : LIKE' ILE BASLAMAZ, ILE BITMEZ, ICERMEZ (WHERE CUSTOMERNAME NOT LIKE 'ALI%') --ILE BITER (WHERE CUSTOMERNAME NOT LIKE '%ALP') --ICERIR (WHERE CUSTOMERNAME NOT LIKE '%ALAN%')
--'NOT IN'      : ICINDE DEGILDIR (WHERE CITY NOT IN('ISTANBUL','ANKARA','BURSA')) --CITY ISTANBUL ANKARA BURSA OLMAYAN BUTUN SATIRLARI GETIR

--SELECT SORGULATALIM
USE ETRADE
GO
SELECT * FROM CUSTOMERS
WHERE CITY IN ('İSTANBUL','ANKARA','BURSA','İZMİR')

--UPDATE KOMUTUNUDA WHERE ISLEINE TABI TUTABILIRIZ 
--GENDER'I E OLANLARI ERKEK OLARAK DEGISTIRELIM
UPDATE CUSTOMERS
SET GENDER='ERKEK'
WHERE GENDER='E'
--SELECT ILE SORGULATIP UPDATE ISLEMI GERCEKLESMISMI BAKALIM
SELECT * FROM CUSTOMERS
--GENDER'I K OLANLARI KADIN OLARAK DEGISTIRELIM
UPDATE CUSTOMERS
SET GENDER='KADIN'
WHERE GENDER='K'
--SELECT ILE SORGULATIP UPDATE ISLEMI GERCEKLESMISMI BAKALIM
SELECT * FROM CUSTOMERS

--WHERE KOMUTUNU DELETE ISLEMINDEDE KULLNABILIRIZ

--ID'SI 18 OLAN KAYIDI SILELIM VE BU SILME ISLEMINDE WHERE KOMUTUNU KULLANARAK YAPALIM 
DELETE
FROM CUSTOMERS
WHERE ID=18
--SELECT ILE SORGULATIP DELETE ISLEMI GERCEKLESMISMI BAKALIM
SELECT * FROM CUSTOMERS
WHERE ID=18
--GORULDUGU GIBI HICBIR SONUC GETIRMEDI NEDEN CUNKU KAYIDI SILDIK INANMIYORSANIZ TABLONUN TAMAMINI SORGULATALIM
SELECT * FROM CUSTOMERS
--GORULDUGU GIBI ID=18 ESIT OLAN KAYIT YOK