/*
SELECT DISTINCT
KOLONADI1,KOLONADI2,KOLONADI3
FROM TABLO_ADI
WHERE <SARTLAR>
*/
-- DISTINCT I SEY OLARAK DUSENEBILIRIZ KUMELER GIBI TEKRAR EDEN DEGER OLMUYACAK SEKILDE SONUC DONDURUR
SELECT 
CITY FROM CUSTOMERS--1002 SONUC TEKRAR EDEN VERILER

SELECT DISTINCT
CITY FROM CUSTOMERS --83 BIRBIRINDEN FARKLI VERILER

SELECT 
CITY,DISTRICT FROM CUSTOMERS 
WHERE CITY='İstanbul'--36 FARKLI DEGER

SELECT DISTINCT
CITY,DISTRICT FROM CUSTOMERS 
WHERE CITY='İstanbul' --22 DEGER ISTANBULDAKI FARKLI FARKLI ILCELER