--ORDER(SIRA) BY SIRALAMA ANLAMIDADIR
/*
SELECT 
KOLON1,KOLON2,KOLON3...
FROM TABLOADI
WHERE<SARTLAR>
ORDER BY KOLON1 ASC,KOLON2 DESC,KOLON3 ASC
--(ASC A-Z ) (DESC Z-A)
*/
SELECT * FROM CUSTOMERS
ORDER BY ID --DEFAULT ASC DIR

SELECT * FROM CUSTOMERS
ORDER BY ID ASC -- A-Z BIRDEN-SONSUZA

SELECT * FROM CUSTOMERS
ORDER BY ID DESC --Z-A SONSUZDAN-BIRE

SELECT * FROM CUSTOMERS
ORDER BY CUSTOMERNAME ASC --A-Z CUSTOMERSNAME'E GORE SIRALA

SELECT * FROM CUSTOMERS
ORDER BY CUSTOMERNAME DESC --Z-A CUSTOMERSNAME'E GORE SIRALA

SELECT * FROM CUSTOMERS
ORDER BY CITY ASC,CUSTOMERNAME ASC -- CIFT KOLON SIRALAMA YAPABILIRIZ MANTIGI CITY A-Z YE SIRALA CUSTOMERNAME ISE CITY YE GORE A-Z YE SIRALA


SELECT * FROM CUSTOMERS
ORDER BY 3 ASC,2 ASC --SUTUN NUMARALARINI GIREREKTE SIRALAYABİLİRİZ